[package]
name = "streamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
hound = "3.5.0"

[[bin]]
name = "streamer"
path = "src/main.rs"

[lib]
name = "lib"
path = "src/lib.rs"
